[package]
name = "rust-delta-polars"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = "0.4.0"
anyhow = "1.0.53"
tokio = "1.16.1"